---
title: "Class 8"
author: "Joseph Sher"
date: "2026-09-21"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    numbered_sections: TRUE
    code_download: TRUE
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Cincy Crashes 
```{r API intro}
httr2::request("https://data.cincinnati-oh.gov/resource/rvmt-pkmq.json") |>
  httr2::req_url_query("$limit" = 5) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> cincy_crashes

```

# FRED API
```{r FREDAPI}
httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json"
  ) |>
  # nothing has been sent yet
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> ohio_jobs
```

# Return the dataframe
```{r dataframe}
jobs_df = ohio_jobs[[13]]

# to get data from Sep 1, 2026
#(a) to get all the data and then filter the rows I want - not most efficient
jobs_df$date = as.Date(jobs_df$date)

jobs_df |>
  # date is a character, so I overwrote the date into a date column
  dplyr::mutate(
    date = lubridate::ymd(date)
  ) |>
  #used filter to determine date
  dplyr::filter(date >= '2026-09-01') -> jobs_df_mod


## b - use the API since it had observaion start
httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json",
    observation_start = "2026-09-01"
  ) |>
  # nothing has been sent yet
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> ohio_jobs_sep_2026
ohio_jobs_sep_2026_df=ohio_jobs_sep_2026[[13]]
```

# USA Jobs
```{r USA Jobs}
httr2::request("https://data.usajobs.gov/api/search") |>
  httr2::req_url_query(Keyword = "Data Analyst", ResultsPerPage = 500) |>
  httr2::req_headers(
    Host = "data.usajobs.gov",
    "User-Agent" = "sherjg@miamioh.edu",
    "Authorization-Key" = Sys.getenv("USAJOBS_API_KEY")
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON(flatten = TRUE) -> usa_jobs_list

usa_df=usa_jobs_list$SearchResult$SearchResultItems

jobs_small = usa_df |>
  dplyr::select(
    title = MatchedObjectDescriptor.PositionTitle,
    department = MatchedObjectDescriptor.DepartmentName,
    agency = MatchedObjectDescriptor.OrganizationName,
    location = MatchedObjectDescriptor.PositionLocationDisplay,
    closes = MatchedObjectDescriptor.ApplicationCloseDate
  )

jobs_small |>
  dplyr::count(department, sort = T) |>
  head(3)

index_data_analyst = jobs_small$title |>
  stringr::str_detect(pattern = "Data Analyst|Data Analytics")

jobs = jobs_small[index_data_analyst, ]
table(jobs$departent)
  
```

