---
title: "Class 13"
author: "Joseph Sher"
date: "2026-10-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plane Crash Example
<https://www.planecrashinfo.com/2025/2025.htm>

```{r tidy_tc_crashes}
year = 2025

crash_url = paste0("https://www.planecrashinfo.com/",year,'/',year,'.htm')

crash_page = rvest::read_html(crash_url, encoding = "ISO-8859-1")

# What we learned last class is that if I were to read this as an HTML table, I have no control on what goes into each column in the resulting data frame -- this makes cleaning it more challenging

crash_page |> rvest::html_elements("tr > td:nth-child(1) > font > a") |>
  rvest::html_text2() -> dates

crash_page |>
  rvest::html_elements("tr > td:nth-child(2) > font") |>
  rvest::html_text2() -> loc_op

crash_page |>
  rvest::html_elements("tr > td:nth-child(4) > font") |>
  rvest::html_text2() -> fatalities

df = data.frame(dates = dates, loc = loc_op[-1], fatalities = fatalities[-1]) |>
  tidyr::separate(loc, into = c("location","operator", sep="\n")  |>
          
                    
  )

df
```

